name: Exploits
description: Detect common exploits
author: StarTux
version: 0.1
website: http://cavetale.com
api-version: 1.13
main: com.winthier.exploits.ExploitsPlugin
depend: []
commands:
  exploits:
    description: Admin interface
    permission: exploits.exploits
    usage: |-
      /<command> hi(ghlight)
        Highlight player placed blocks.
      /<command> debug
        Toggle debug mode.
permissions:
  exploits.exploits:
    description: Use the /exploits command
    default: op
