main: com.winthier.exploits.ExploitsPlugin
name: Exploits

version: 0.1
api-version: '1.21'

description: Remember if blocks are player placed.
author: StarTux
website: http://cavetale.com

depend: [Core]
softdepent: []

commands:

  exploits:
    description: Admin interface
    permission: exploits.exploits
    usage: |-
      /<command> hi(ghlight)
        Highlight player placed blocks.
      /<command> debug
        Spam debug info.

permissions:

  exploits.exploits:
    description: Use the /exploits command
    default: op
